INSERT INTO tblOrderStatusDescription VALUES('Sipariş Alındı','SQL Transaction',GETDATE(),NULL,NULL)
INSERT INTO tblOrderStatusDescription VALUES('Yola Çıktı','SQL Transaction',GETDATE(),NULL,NULL)
INSERT INTO tblOrderStatusDescription VALUES('Dağıtım Merkezinde','SQL Transaction',GETDATE(),NULL,NULL)
INSERT INTO tblOrderStatusDescription VALUES('Dağıtıma Çıktı','SQL Transaction',GETDATE(),NULL,NULL)
INSERT INTO tblOrderStatusDescription VALUES('Teslim Edildi','SQL Transaction',GETDATE(),NULL,NULL)
INSERT INTO tblOrderStatusDescription VALUES('Teslim Edilemedi','SQL Transaction',GETDATE(),NULL,NULL)